spring.application.name=aplicacion-tierra-nativa
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:tierranativa
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
server.port=8080


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tierranativa.dev@gmail.com
spring.mail.password=jcpw pugl vjzf vaxl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

spring.mandatory-file-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force-response=true

tierranativa.contact.whatsapp=5491171256075
tierranativa.contact.default-message=\u00a1Hola Tierra Nativa! \ud83c\udf3f Me encantar\u00eda conocer m\u00e1s sobre sus experiencias y paquetes tur\u00edsticos para planificar mi pr\u00f3xima aventura.